---
apiVersion: v1
kind: Pod
metadata:
  name: nettools
  labels:
    env: prod
spec:
  containers:
  - name: nettools
    image: zerthimon/nettools:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
